# Generated by Django 5.2.1 on 2025-05-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymetric',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
